

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - cowrie_logs:/cowrie/logs
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elk_network

  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    environment:
      - COWRIE_ELASTICSEARCH_HOST=http://elasticsearch:9200
    volumes:
      - cowrie_logs:/cowrie/logs
      - ./cowrie.cfg:/cowrie/cowrie.cfg
    ports:
      - "22:22"
      - "23:23"
    networks:
      - elk_network

volumes:
  es_data:
    driver: local
  cowrie_logs:
    driver: local

networks:
  elk_network:
    driver: bridge
